Features
sergioobolevich/Project-Library-Collaborative pull request #1
Opened 2021-01-22 22:03 UTC by chubaquelo

In this project, we did a simple application in javascript using localStorage to save items on browser memory.
We added a toggle form that shows or hides the new book form.
We used a data- index property in the HTML element to be able to match it in the books array.
We added a read/unread and a delete button for each book.
A simple layout was created using flexbox, so the application is responsive design.

2021-01-23 00:48 UTC, krys2fa requested changes
## Great job @t-yanick and @chubaquelo  👏 
Your project is coming along nicely. 💪 
Just a few more adjustments to complete the project. They are seen below and in the comments.
### Status: Changes Required ♻️ 

- [x] [REQUIRED] The form should have an `author` field.
- [x] [OPTIONAL]  The form used to create a book should have validations, you should not be able to create an empty book which is the case now.

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2021-01-23 00:48 UTC, krys2fa commented on app.js
> +  // addBookToLibrary(book);
- [ ] [REQUIRED] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)). The same applies to line 160.

2021-01-23 00:48 UTC, krys2fa commented on app.js
> +  let book = {title, desc, pages, status};
- [ ] [REQUIRED] Book should have a constructor ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/book_array_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library)).

2021-01-25 21:12 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-25 21:12 UTC, Spayco commented on index.html
> +        <input type="checkbox" id="read-status" name="read-status" value="Book">
- [ ] it would be better if the number of pages `<input>` is a `type` of `number`, not `text`, to reduce errors.

2021-01-27 02:20 UTC, merged